# -*- coding: utf-8 -*-
"""데이터 분석을 위한 python 이해 practice1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YghIpTgb5zmV7RaE88KhZW0i1w6YJ2b8

# 심화 실습1

파일명 : 판교_2반_양시온.py
작성자 : 양시온
작성일 : 2026.08.03

목적
- Python 자료구조 및 함수 활용 실습
- 매출 데이터를 이용한 데이터 처리 및 분석

사용 라이브러리
- json, sys
- Counter, defaultdict
"""

#라이브러리 불러오기
import json
import sys
from collections import Counter, defaultdict

#데이터 불러오기
exec(open("Python_Practice1_Data.json", encoding="utf-8").read())

print(sales[:5])

# 1) 리스트/딕셔너리 컴프리헨션
# - python_Practice1_Data.json(Sales) 리스트에서
# amount >= 1000만

# amount가 1000 이상인 거래만 추출
sales_up_1000 = [
    sale for sale in sales if sale["amount"] >= 1000
]

#amount 100이상 거래 print
print(sales_up_1000[:5])
print(f"1000원 이상 거래수 : {len(sales_up_1000)}")

#지역별 총매출 dict를 컴프리헨션으로 계산

# 중복을 제거하여 지역 목록 생성
#집합을 사용하여 중복제거. +)딕셔너리 컴프리헨션
regions = {
    sale["region"]
    for sale in sales
}

# 지역별 총매출 계산
region_total = {
    region: sum(
        sale["amount"]
        for sale in sales
        if sale["region"] == region
    )
    for region in regions
}

#지역 총 매출 print
print(region_total)

#2)Counter + defaultdict
# Counter로 지역별 거래 건수를, defaultdict로 카테고리별 amount 리스트

#Counter 를 이용하여 지역별 거래 건수 계산
region_count = Counter(
    sale["region"]
    for sale in sales
)

# 지역별 거래 건수 print
print(region_count)

#defaultdict를 이용하여 카테고리별 amount 리스트 생성
category_amount = defaultdict(list)

for sale in sales:
  category_amount[sale["category"]].append (sale["amount"])

# 카테고리 별 amount 리스트 print
print(dict(category_amount))

#3) 제너레이터 - 메모리 비교
# amount > 1000 인 행만 yield 하는 제너레이터를 작성하고, 리스트 버전과 메모리 크기를 비교

# amount > 1000 거래를 하나씩 반환하는 제너레이터 함수

#List 생성
# List 생성
high_sales_list = [
    sale
    for sale in sales
    if sale["amount"] > 1000
]


#Generator 함수
def high_sales_generator(data):
    for sale in data:
        if sale["amount"] > 1000:
            yield sale

# Generator 객체 생성
high_sales_gen = high_sales_generator(sales)

# 메모리 크기 비교
print("List 메모리 :", sys.getsizeof(high_sales_list), "bytes")
print("Generator 메모리 :", sys.getsizeof(high_sales_gen), "bytes")

# Generator가 List보다 메모리를 적게 사용하는지 확인
assert sys.getsizeof(high_sales_gen) < sys.getsizeof(high_sales_list)

# Generator가 List보다 메모리를 적게 사용하는지 확인
assert sys.getsizeof(high_sales_gen) < sys.getsizeof(high_sales_list)

print("generator sys.getsizeof < list 확인")

# 4) 종합 - 월별 카테고리 매출 집계
#sales 데이터를 month·category 기준으로 그룹핑해 총매출 dict를 완성 (컴프리헨션 + defaultdict)

# 월별 · 카테고리별 총매출을 저장할 defaultdict 생성
monthly_category_sales = defaultdict(lambda: defaultdict(int))

# month와 category를 기준으로 amount 합계 계산
for sale in sales:
    monthly_category_sales[sale["month"]][sale["category"]] += sale["amount"]

# 결과 출력
for month, category in monthly_category_sales.items():
    print(month, dict(category))