# -*- coding: utf-8 -*-
"""데이터 분석을 위한 python 이해 practice2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EvxIETpSjzA2Bn4L9MZEk8ZdbBpKFNG4

# 심화 실습 2
"""

# ==========================================================
# 파일명 : 판교_2반_양시온.py
# 작성자 : 양시온
# 작성일 : 2026.08.03
# 과제명 : Python Practice 2
# 목적 : JSON 데이터 로드, Pydantic 검증, 파일 입출력 및 예외 처리 실습
# ==========================================================

# 라이브러리 불러오기
import json
import csv
import logging
from pydantic import BaseModel, Field, ValidationError

#Logger 설정
logging.basicConfig(leve = logging.INFO)
logger = logging.getLogger(__name__)

"""#  1)예외 처리 + 파일 읽기
함수명 : safe_load_csv()

완성파일 없으면 None 반환·logger.error , 성공 시 dict 리스트 반환·logger.info, finally에서 '로딩 종료' 출력
"""

# 파일 읽기
def safe_load_csv(file_path):
  try:
    with open(file_path, "r", encoding = "utf-8") as f:
      data = json.load(f)

      logger.info(f"{len(data)}건 로딩 성공")
      return data

  except FileNotFoundError:
    logger.error(f"{file_path} 파일을 찾을 수 없습니다.")
    return None

  finally:
    print("로딩 종료")

#파일 존재 여부 확인
assert safe_load_csv("없는파일.json") is None

# 실제 데이터 로드
raw_data = safe_load_csv("/content/Python_Practice2_Data.json")

"""## 2)Pydantic v2 스키마 정의

SalesRecord 모델을 완성

month·region: 비어있으면 안 됨

amount: 0 초과

category: 없어도 됨

"""

# Pydantic 모델
class SalesRecord(BaseModel):
    month: str = Field(min_length=1)    # month 비어 있으면 안됨
    region: str = Field(min_length=1)   # region 비어 있으면 안됨
    amount: float = Field(gt=0)         # amount 0초과
    category: str | None = None         # category 없어도 됨

"""## 3) 검증 파이프라인 (valid / errors 분리)

raw_data를 순회하며 SalesRecord로 변환

성공→valid, 실패→errors({row, error})
리스트
"""

#Validation

valid = []
errors = []

for idx, row in enumerate(raw_data):
  try:
    record = SalesRecord(**row)
    valid.append(record)

  except ValidationError as e:
      print(e)

      errors.append({
          "row": idx,
          "error": str(e)
      })

print(f"valid : {len(valid)}건")
print(f"errors : {len(errors)}건")

"""## 4) 결과 파일 저장+ 재로딩 확인
valid 코드를 CSV로, errors를 JSON으로 저장하고 다시 읽어 건수를 검증

"""

# valid CSV 저장
with open("valid.csv", "w", newline="", encoding="utf-8-sig") as f:
    writer = csv.DictWriter(
        f,
        fieldnames=["month", "region", "amount", "category"]
    )

    writer.writeheader()

    for record in valid:
        writer.writerow(record.model_dump())

# errors JSON 저장
with open("errors.json", "w", encoding="utf-8") as f:
    json.dump(
        errors,
        f,
        ensure_ascii=False,
        indent=4
    )

# CSV 재로딩
reloaded = []

with open("valid.csv", "r", encoding="utf-8-sig") as f:
    reader = csv.DictReader(f)

    for row in reader:
        reloaded.append(row)

print(f"재로딩 건수 : {len(reloaded)}")

assert len(reloaded) == len(valid)

